import * as fs from 'fs';
import * as path from 'path';

export interface AdrSummary {
  id: string;
  title: string;
  /** tc-* frontmatter fields joined as a compact string, or empty. */
  tcContext: string;
}

const MAX_ADRS = 20;

/**
 * Recursively scans the `docs/` folder under `workspaceRoot` for markdown
 * files and returns a summary for each ADR found. Returns an empty array if
 * `docs/` does not exist.
 *
 * Each summary contains the ADR id, the top-level `#` heading as the title,
 * and any `tc-*` frontmatter fields (generated by the sister extension) as
 * additional context for the model.
 */
export function findAdrs(workspaceRoot: string): AdrSummary[] {
  const docsDir = path.join(workspaceRoot, 'docs');
  if (!fs.existsSync(docsDir) || !fs.statSync(docsDir).isDirectory()) {
    return [];
  }
  return collectMdFiles(docsDir)
    .slice(0, MAX_ADRS)
    .flatMap((f) => {
      const s = parseAdr(f);
      return s ? [s] : [];
    });
}

function collectMdFiles(dir: string): string[] {
  const results: string[] = [];
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectMdFiles(full));
    } else if (/\.md$/i.test(entry.name)) {
      results.push(full);
    }
  }
  return results;
}

function parseAdr(filePath: string): AdrSummary | null {
  let raw: string;
  try {
    raw = fs.readFileSync(filePath, 'utf-8');
  } catch {
    return null;
  }

  const lines = raw.split('\n');
  const { frontmatter, bodyStart } = extractFrontmatter(lines);

  // Title: first `#` heading in the markdown body
  const headingLine = lines.slice(bodyStart).find((l) => /^#\s/.test(l));
  const title =
    headingLine?.replace(/^#+\s*/, '').trim() ??
    frontmatter['title'] ??
    path.basename(filePath, '.md');

  // ADR id: leading digits in filename (e.g. 0007-name.md → ADR-0007)
  const fileDigits = path.basename(filePath).match(/^(\d+)/)?.[1];
  const id = fileDigits
    ? `ADR-${fileDigits.padStart(4, '0')}`
    : path.basename(filePath, '.md');

  // tc-* fields from frontmatter (sister-extension generated)
  const tcEntries = Object.entries(frontmatter)
    .filter(([k]) => k.startsWith('tc-'))
    .map(([k, v]) => `${k}: ${v}`);
  const tcContext = tcEntries.join(' | ');

  return { id, title, tcContext };
}

/**
 * Strips a leading YAML frontmatter block (`---` ... `---`) from `lines` and
 * returns a flat key→value map of its scalar entries plus the line index where
 * the markdown body starts.
 */
function extractFrontmatter(lines: string[]): {
  frontmatter: Record<string, string>;
  bodyStart: number;
} {
  const frontmatter: Record<string, string> = {};
  if (lines[0]?.trim() !== '---') {
    return { frontmatter, bodyStart: 0 };
  }
  const end = lines.findIndex((l, i) => i > 0 && l.trim() === '---');
  if (end === -1) {
    return { frontmatter, bodyStart: 0 };
  }
  let currentKey: string | null = null;
  const listItems: string[] = [];

  const flushList = () => {
    if (currentKey && listItems.length > 0) {
      frontmatter[currentKey] = listItems.join(', ');
    }
    currentKey = null;
    listItems.length = 0;
  };

  for (const line of lines.slice(1, end)) {
    const scalar = line.match(/^([\w-]+):\s*(.+)$/);
    const listKey = line.match(/^([\w-]+):\s*$/);
    const listItem = line.match(/^\s+-\s+(.+)$/);

    if (scalar) {
      flushList();
      frontmatter[scalar[1]] = scalar[2].trim();
    } else if (listKey) {
      flushList();
      currentKey = listKey[1];
    } else if (listItem && currentKey) {
      listItems.push(listItem[1].trim());
    } else {
      flushList();
    }
  }
  flushList();
  return { frontmatter, bodyStart: end + 1 };
}
